# Generated by Django 6.0.4 on 2026-04-24 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('discription', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('fieild_of_activity', models.CharField(choices=[('it', 'IT'), ('marketing', 'Маркетинг'), ('production', 'Производство')], max_length=50, verbose_name='Сфера деятельности')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_company', to=settings.AUTH_USER_MODEL, verbose_name='Директор')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('discription', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('status', models.IntegerField(choices=[(1, 'Новая'), (2, 'Принята'), (3, 'На проверке'), (4, 'Завершена'), (5, 'Отложена'), (6, 'Просрочена'), (7, 'Возвращена')], default=1, verbose_name='Статус')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.company', verbose_name='Компания')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
        ),
    ]
